## Матричный метод

Создадим матрицу

In [9]:
import numpy as np

K = np.array([[-4., 8., -3.], [2., 7., 9.], [2., 1., -7.]])
K

array([[-4.,  8., -3.],
       [ 2.,  7.,  9.],
       [ 2.,  1., -7.]])

## Вектор матрицы

In [12]:
L = np.array([1., 4., 8.])
L

array([1., 4., 8.])

###  Для решения системы воспользуемся функцией numpy.linalg.solve

In [14]:
np.linalg.solve(K, L)

array([ 1.71374046,  0.77862595, -0.54198473])