# Свойства матричных вычислений

In [10]:
import numpy as np

In [11]:
m = [[7, 1, 5, 8], [1, 4, 17, 6], [3, 3, 3, 3], [6, 11, 0, 0]]
A = np.array(m)
A

array([[ 7,  1,  5,  8],
       [ 1,  4, 17,  6],
       [ 3,  3,  3,  3],
       [ 6, 11,  0,  0]])

In [12]:
l = [[4, 11, 4, 1], [7, 22, 4, 2], [5, 8, 8, 17], [4, 1, 8, 19]]
B = np.array(l)
B

array([[ 4, 11,  4,  1],
       [ 7, 22,  4,  2],
       [ 5,  8,  8, 17],
       [ 4,  1,  8, 19]])

In [13]:
k = [[1, 2, 44, 7], [17, 7, 2, 11], [8, 2, 8, 9], [8, 9, 9, 1]]
C = np.array(k)
C

array([[ 1,  2, 44,  7],
       [17,  7,  2, 11],
       [ 8,  2,  8,  9],
       [ 8,  9,  9,  1]])

## Транспонированиe

In [14]:
A.transpose()

array([[ 7,  1,  3,  6],
       [ 1,  4,  3, 11],
       [ 5, 17,  3,  0],
       [ 8,  6,  3,  0]])

In [15]:
A.T

array([[ 7,  1,  3,  6],
       [ 1,  4,  3, 11],
       [ 5, 17,  3,  0],
       [ 8,  6,  3,  0]])

In [16]:
(A.T).T

array([[ 7,  1,  5,  8],
       [ 1,  4, 17,  6],
       [ 3,  3,  3,  3],
       [ 6, 11,  0,  0]])

### Транспонирование суммы матриц равно сумме транспонированных матриц:

In [17]:
(A+B).T


array([[11,  8,  8, 10],
       [12, 26, 11, 12],
       [ 9, 21, 11,  8],
       [ 9,  8, 20, 19]])

In [18]:
A.T+B.T

array([[11,  8,  8, 10],
       [12, 26, 11, 12],
       [ 9, 21, 11,  8],
       [ 9,  8, 20, 19]])

### Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке

In [19]:
(A.dot(B)).T

array([[ 92, 141,  60, 101],
       [147, 241, 126, 308],
       [136, 204,  72,  68],
       [246, 412, 117,  28]])

In [20]:
(B.T).dot(A.T)

array([[ 92, 141,  60, 101],
       [147, 241, 126, 308],
       [136, 204,  72,  68],
       [246, 412, 117,  28]])

### Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу

In [21]:
t = 11
(t * A).T

array([[ 77,  11,  33,  66],
       [ 11,  44,  33, 121],
       [ 55, 187,  33,   0],
       [ 88,  66,  33,   0]])

In [22]:
t * (A.T)

array([[ 77,  11,  33,  66],
       [ 11,  44,  33, 121],
       [ 55, 187,  33,   0],
       [ 88,  66,  33,   0]])

### Определители исходной и транспонированной матрицы совпадают:

In [23]:
A_det = np.linalg.det(A)
print(format(A_det, '.9g'))

636


In [24]:
A_T_det = np.linalg.det(A.T)
print(format(A_T_det, '.9g'))

636


### Умножение матрицы на число

In [25]:
14 * A

array([[ 98,  14,  70, 112],
       [ 14,  56, 238,  84],
       [ 42,  42,  42,  42],
       [ 84, 154,   0,   0]])

### Произведение единицы и любой заданной матрицы равно заданной матрице:

In [26]:
1 * A

array([[ 7,  1,  5,  8],
       [ 1,  4, 17,  6],
       [ 3,  3,  3,  3],
       [ 6, 11,  0,  0]])

In [27]:
0 * A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
(1 + 2) * A

array([[21,  3, 15, 24],
       [ 3, 12, 51, 18],
       [ 9,  9,  9,  9],
       [18, 33,  0,  0]])

In [29]:
3 * A + 5 * A

array([[ 56,   8,  40,  64],
       [  8,  32, 136,  48],
       [ 24,  24,  24,  24],
       [ 48,  88,   0,   0]])

In [30]:
4 * (A + B)

array([[ 44,  48,  36,  36],
       [ 32, 104,  84,  32],
       [ 32,  44,  44,  80],
       [ 40,  48,  32,  76]])

In [31]:
4 * A + 4 * B

array([[ 44,  48,  36,  36],
       [ 32, 104,  84,  32],
       [ 32,  44,  44,  80],
       [ 40,  48,  32,  76]])

### Сложение матриц

In [32]:
A + B

array([[11, 12,  9,  9],
       [ 8, 26, 21,  8],
       [ 8, 11, 11, 20],
       [10, 12,  8, 19]])

In [33]:
B + A

array([[11, 12,  9,  9],
       [ 8, 26, 21,  8],
       [ 8, 11, 11, 20],
       [10, 12,  8, 19]])

In [34]:
A + (B + C)

array([[12, 14, 53, 16],
       [25, 33, 23, 19],
       [16, 13, 19, 29],
       [18, 21, 17, 20]])

In [35]:
(A + B) + C

array([[12, 14, 53, 16],
       [25, 33, 23, 19],
       [16, 13, 19, 29],
       [18, 21, 17, 20]])

In [36]:
A + (-1)*A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Диаграмма матричного умножения



In [37]:
A.dot(B)

array([[ 92, 147, 136, 246],
       [141, 241, 204, 412],
       [ 60, 126,  72, 117],
       [101, 308,  68,  28]])

### Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция

In [38]:
A.dot(B.dot(C))

array([[ 5647,  3699,  7644,  3731],
       [ 9166,  6085, 12026,  5886],
       [ 3714,  2199,  4521,  2571],
       [ 6105,  2746,  5856,  4735]])

In [39]:
(A.dot(B)).dot(C)

array([[ 5647,  3699,  7644,  3731],
       [ 9166,  6085, 12026,  5886],
       [ 3714,  2199,  4521,  2571],
       [ 6105,  2746,  5856,  4735]])

### Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [40]:
A.dot(B+C)

array([[220, 250, 558, 359],
       [394, 359, 446, 622],
       [162, 186, 261, 201],
       [294, 397, 354, 191]])

In [41]:
A.dot(B)+A.dot(C)

array([[220, 250, 558, 359],
       [394, 359, 446, 622],
       [162, 186, 261, 201],
       [294, 397, 354, 191]])

In [42]:
A.dot(B)

array([[ 92, 147, 136, 246],
       [141, 241, 204, 412],
       [ 60, 126,  72, 117],
       [101, 308,  68,  28]])

In [43]:
B.dot(A)

array([[ 57,  71, 219, 110],
       [ 95, 129, 421, 200],
       [169, 248, 185, 112],
       [167, 241,  61,  62]])

#### Произведение заданной матрицы на единичную равно исходной матрице

In [44]:
E = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')
E.dot(A)

matrix([[ 7,  1,  5,  8],
        [ 1,  4, 17,  6],
        [ 3,  3,  3,  3],
        [ 6, 11,  0,  0]])

In [45]:
A.dot(E)

matrix([[ 7,  1,  5,  8],
        [ 1,  4, 17,  6],
        [ 3,  3,  3,  3],
        [ 6, 11,  0,  0]])

In [46]:
Z = np.matrix('0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0')
Z.dot(A)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [47]:
A.dot(Z)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

#### Определитель матрицы

In [48]:
np.linalg.det(A)

636.0000000000007

#### Определитель матрицы остается неизменным при ее транспонировании:


In [49]:
round(np.linalg.det(A), 3)

636.0

In [50]:
round(np.linalg.det(A.T), 3)

636.0

### Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [51]:
N = np.matrix('1 0 1; 0 0 0; 21 2 1')
np.linalg.det(N)

0.0

#### Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [52]:
N = np.matrix('9 8 7; 5 6 4; 9 8 7')
np.linalg.det(N)

0.0

#### Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число

In [53]:
N = np.matrix('4 1 12; 7 1 2; 9 3 3')
k = 3
M = N.copy()
M[2, :] = k * M[2, :]
print(M)

[[ 4  1 12]
 [ 7  1  2]
 [27  9  9]]


In [54]:
det_N = round(np.linalg.det(N), 3)
det_M = round(np.linalg.det(M), 3)

In [55]:
det_N * k

387.0

In [56]:
det_M

387.0

#### Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц

In [57]:
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[ 7  1  5  8]
 [ 8 26 21  8]
 [ 3  3  3  3]
 [ 6 11  0  0]]


In [58]:
A

array([[ 7,  1,  5,  8],
       [ 1,  4, 17,  6],
       [ 3,  3,  3,  3],
       [ 6, 11,  0,  0]])

In [59]:
B

array([[ 4, 11,  4,  1],
       [ 7, 22,  4,  2],
       [ 5,  8,  8, 17],
       [ 4,  1,  8, 19]])

#### Обратная матрица

In [60]:
N = np.matrix('6 9; -12 18')
np.linalg.inv(N)

matrix([[ 0.08333333, -0.04166667],
        [ 0.05555556,  0.02777778]])

In [61]:
np.linalg.inv(N.T)

matrix([[ 0.08333333,  0.05555556],
        [-0.04166667,  0.02777778]])

In [62]:
(np.linalg.inv(N)).T

matrix([[ 0.08333333,  0.05555556],
        [-0.04166667,  0.02777778]])

In [63]:
M = np.matrix('3. 6.; 5. 10.')
N = np.matrix('-4. 8.; 3. -9.')
np.linalg.inv(M.dot(N))

matrix([[ 1.40737488e+15, -8.44424930e+14],
        [ 2.81474977e+14, -1.68884986e+14]])

In [64]:
np.linalg.inv(N).dot(np.linalg.inv(M))

matrix([[-9.38249922e+14,  5.62949953e+14],
        [-1.87649984e+14,  1.12589991e+14]])